<?php

namespace lsa\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function search($user){      
        $qb = $this->createQueryBuilder('u')  
               ->where("u.username LIKE :user OR u.firstname LIKE :user OR u.lastname LIKE :user OR u.email LIKE :user ")
               ->setParameter('user', '%'.$user.'%');             
 
        return $qb->getQuery()->getResult();
    }
}
