#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
##fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
#

login:
    pattern:   /login
    defaults:  { _controller: UserBundle:User:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout    
#rout user
portfolio_user_admin:
    pattern: /admin/user
    defaults: {_controller: UserBundle:User:index } 

portfolio_user_add_admin:
    pattern: /admin/user/add
    defaults: {_controller: UserBundle:User:add }
        
portfolio_user_edit_admin:
    pattern: /admin/user/edit/{user}
    defaults: {_controller: UserBundle:User:edit }
    requirements:
        level: \d+

portfolio_user_delete_admin:
    pattern: /admin/user/delete/{user}
    defaults: {_controller: UserBundle:User:delete }
    requirements:
        level: \d+ 
    
