parameters:
#    user.example.class: lsa\UserBundle\Example

services:
#    user.example:
#        class: %user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
   #lsa_user.registration.form.type:
    #    class: lsa\UserBundle\Form\UserType
     #   arguments: [%fos_user.model.user.class%]
      #  tags:
       #     - { name: form.type, alias: lsa_userbundle_user }
