<?php

namespace lsa\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EducationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationsRepository extends EntityRepository
{
}
